#!/usr/bin/env python3
"""
Lucy AI Agent — Modular HTTP Endpoint Scanner
Generated by Security Engineering Architect

Usage: python3 http_scanner.py --target http://localhost:8080 --wordlist /wordlists/common.txt
"""
import argparse
import json
import logging
import socket
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urljoin, urlparse

import urllib.request


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

def setup_logging(log_dir: str = "/workspace/logs") -> Path:
    """Configure structured JSON logging to /workspace/logs."""
    log_path = Path(log_dir)
    log_path.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    log_file = log_path / f"http_scan_{timestamp}.json"

    handler = logging.FileHandler(log_file)
    handler.setFormatter(logging.Formatter("%(message)s"))

    logger = logging.getLogger("http_scanner")
    logger.setLevel(logging.INFO)
    logger.addHandler(handler)
    return log_file


def log_result(logger: logging.Logger, finding: dict) -> None:
    """Append a structured JSON finding to the log file."""
    record = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "tool": "http_scanner",
        "status": finding.get("status", "info"),
        "target": finding.get("target"),
        "finding": finding,
    }
    logger.info(json.dumps(record))


# ---------------------------------------------------------------------------
# Logic
# ---------------------------------------------------------------------------

def resolve_host(target: str) -> dict:
    """Resolve hostname to IP and check basic connectivity."""
    parsed = urlparse(target)
    hostname = parsed.hostname or target
    port = parsed.port or (443 if parsed.scheme == "https" else 80)

    result = {
        "target": target,
        "hostname": hostname,
        "port": port,
        "scheme": parsed.scheme or "http",
    }

    try:
        ip = socket.gethostbyname(hostname)
        result["ip"] = ip
        result["status"] = "success"
    except socket.gaierror as exc:
        result["ip"] = None
        result["status"] = "error"
        result["error"] = str(exc)

    return result


def probe_endpoint(base_url: str, path: str, timeout: int = 10) -> dict:
    """Probe a single endpoint and return structured results."""
    url = urljoin(base_url.rstrip("/") + "/", path.lstrip("/"))
    finding = {
        "target": url,
        "path": path,
        "status": "unknown",
        "status_code": None,
        "content_length": None,
        "response_time_ms": None,
        "error": None,
    }

    try:
        start = time.time()
        req = urllib.request.Request(url, method="GET", headers={
            "User-Agent": "Lucy-AI-Agent/1.0 (Security Research)",
            "Accept": "*/*",
        })
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            finding["status_code"] = resp.status
            finding["content_length"] = len(resp.read())
            finding["response_time_ms"] = round((time.time() - start) * 1000, 2)
            finding["status"] = "success"
    except urllib.error.HTTPError as exc:
        finding["status_code"] = exc.code
        finding["response_time_ms"] = round((time.time() - start) * 1000, 2)
        finding["status"] = "success" if exc.code in (401, 403, 404) else "warning"
        finding["error"] = f"HTTP {exc.code}"
    except Exception as exc:
        finding["status"] = "error"
        finding["error"] = str(exc)

    return finding


def discover_endpoints(base_url: str, wordlist: list[str], max_workers: int = 10) -> list[dict]:
    """Discover endpoints using a wordlist with concurrent workers."""
    findings = []
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(probe_endpoint, base_url, path): path for path in wordlist}
        for future in as_completed(futures):
            findings.append(future.result())
    return findings


def default_wordlist() -> list[str]:
    """Return a minimal default wordlist for quick scans."""
    return [
        "/", "/api", "/api/v1", "/health", "/status", "/docs", "/swagger",
        "/admin", "/login", "/register", "/config", "/.env", "/robots.txt",
        "/sitemap.xml", "/graphql", "/wp-admin", "/phpmyadmin", "/actuator",
        "/metrics", "/prometheus", "/debug", "/test", "/dev", "/staging",
    ]


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description="Lucy AI Agent — HTTP Endpoint Scanner")
    parser.add_argument("--target", required=True, help="Base URL to scan (e.g., http://localhost:8080)")
    parser.add_argument("--wordlist", help="Path to wordlist file (one path per line)")
    parser.add_argument("--workers", type=int, default=10, help="Concurrent workers (default: 10)")
    parser.add_argument("--timeout", type=int, default=10, help="Request timeout in seconds (default: 10)")
    parser.add_argument("--output", default="/workspace/logs", help="Output directory for JSON logs")
    args = parser.parse_args()

    # Setup logging
    log_file = setup_logging(args.output)
    logger = logging.getLogger("http_scanner")

    print(f"[*] Lucy HTTP Scanner starting...")
    print(f"[*] Target: {args.target}")
    print(f"[*] Log file: {log_file}")

    # Resolve host
    host_info = resolve_host(args.target)
    log_result(logger, host_info)
    print(f"[+] Host: {host_info.get('hostname')} -> {host_info.get('ip')}:{host_info.get('port')}")

    # Load wordlist
    if args.wordlist and Path(args.wordlist).exists():
        with open(args.wordlist, "r") as f:
            wordlist = [line.strip() for line in f if line.strip() and not line.startswith("#")]
    else:
        wordlist = default_wordlist()
        print(f"[*] Using default wordlist ({len(wordlist)} paths)")

    # Scan
    print(f"[*] Scanning {len(wordlist)} endpoints with {args.workers} workers...")
    findings = discover_endpoints(args.target, wordlist, args.workers)

    # Log and summarize
    success_count = sum(1 for f in findings if f["status"] == "success")
    error_count = sum(1 for f in findings if f["status"] == "error")
    warning_count = sum(1 for f in findings if f["status"] == "warning")

    for finding in findings:
        log_result(logger, finding)
        if finding["status_code"] and finding["status_code"] < 400:
            print(f"[+] {finding['path']:30} -> {finding['status_code']} ({finding['response_time_ms']}ms)")
        elif finding["status_code"]:
            print(f"[-] {finding['path']:30} -> {finding['status_code']} ({finding['error']})")
        else:
            print(f"[!] {finding['path']:30} -> ERROR ({finding['error']})")

    summary = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "tool": "http_scanner",
        "target": args.target,
        "status": "success",
        "total_scanned": len(wordlist),
        "success": success_count,
        "warnings": warning_count,
        "errors": error_count,
        "log_file": str(log_file),
    }
    log_result(logger, summary)

    print(f"\n[*] Scan complete.")
    print(f"    Success: {success_count} | Warnings: {warning_count} | Errors: {error_count}")
    print(f"    Log: {log_file}")

    return 0 if error_count == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
